# Generated by Django 3.2.9 on 2021-11-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='images/allien.png', null=True, upload_to='images/'),
        ),
    ]
